### ISSUE TITLE
favourites

### ISSUE THREAD

**Issue by sysadmiral** [KGIF/KGIF#1]
Add a way to favourite or star gifs

**Comment by KarimHmaissi** [comment]
Added favourites: https://github.com/KGIF/KGIF/commit/9390f6a4d1575408141fc53d0610d40e691bc1a0

Additional features in scope:
Remove favourites.
Show favourites alongside results from search as opposed to above.

**Comment by KarimHmaissi** [comment]
Remove favourites added.
Favourite gifs are now persisted to local storage. 
https://github.com/KGIF/KGIF/commit/f327da9bf12e9eb3aa0538babc7958bda7a35dee
